### ISSUE TITLE
Use POST instead of GET 

### ISSUE THREAD

**Issue by jkbrzt** [stochastic-technologies/django-loginas#22]
Thanks for a very useful app!  

I think the user switch should happen on a `POST` request. It's both a more appropriate HTTP method for this type of requests, but more importantly it will ensure that [CSRF check](https://docs.djangoproject.com/en/1.7/ref/contrib/csrf/) is performed. As it is now, anybody can change the user for me just by knowing the URL and embedding an image to a page I visit.

**Comment by skorokithakis** [comment]
That's true, but then you won't be able to use the admin link to do it. Where would the interface element go?
