### ISSUE TITLE
AttributeError When Using "is_admin" in "CAN_LOGIN_AS" via Readme

### ISSUE THREAD

**Issue by Hybridx24** [stochastic-technologies/django-loginas#27]
In the Readme file there is the following line:
`CAN_LOGIN_AS = lambda request, target_user: request.user.is_admin and not target_user.is_admin`

using Django 1.8, I received an `AttributeError` that `is_admin` is not a valid attribute ("`'User' object has no attribute 'is_admin'`"), so I changed it to `is_superuser` and it now works. Not sure if `is_admin` worked in older versions, but it seems to be broken in 1.8... otherwise, amazing package!

**Comment by skorokithakis** [comment]
Changed, thanks for the heads up!
