### ISSUE TITLE
Add support for custom username field

### ISSUE THREAD

**Issue by paambaati** [stochastic-technologies/django-loginas#37]
Django supports customizing the `User` model, and also the `username` field in it. Allow django-loginas to support it, instead of assuming it will always be called 'username'.

@skorokithakis I've submitted a PR (See #36) for this.

**Comment by skorokithakis** [comment]
Merged, thanks!

**Comment by skorokithakis** [comment]
Released in v0.2.2.

**Comment by paambaati** [comment]
![](https://media.giphy.com/media/3o85xzM0kQsQE01teM/giphy.gif)
