### ISSUE TITLE
Login as user is never disconnected

### ISSUE THREAD

**Issue by palmitoto** [stochastic-technologies/django-loginas#41]
If i login as another user. When i log out, i retrieve my former user.
But then, when i logout again, i'm still connected.

The user session flag is never removed from session. Why ?

Sincerely,

F.P

**Comment by skorokithakis** [comment]
Ah, yes, you are correct, the session flag is never cleared after you are logged back in. It should be deleted in the `try` block. Would you like to submit a PR?

**Comment by palmitoto** [comment]
PR submitted.

**Comment by palmitoto** [comment]
PR accepted and merged !
